all: cFactorial javaFactorial.class

cFactorial: cFactorial.c

javaFactorial.class: javaFactorial.java
	javac javaFactorial.java
	
clean: cFactorial javaFactorial.class
	rm cFactorial javaFactorial.class
