all : cBubbleSort cBubbleSortOpt javaBubbleSort.class

cBubbleSort: cBubbleSort.c

cBubbleSortOpt: cBubbleSortOpt.c

javaBubbleSort.class: javaBubbleSort.java
	javac javaBubbleSort.java
	
clean:
	rm cBubbleSort cBubbleSortOpt javaBubbleSort.class
