all: cGnomeSort javaGnomeSort.class

cGnomeSort: cGnomeSort.c

javaGnomeSort.class: javaGnomeSort.java
	javac javaGnomeSort.java

clean: cGnomeSort javaGnomeSort.class
	rm cGnomeSort javaGnomeSort.class
